services:
  questdb:
    image: questdb/questdb:8.2.3
    container_name: trading_demo_questdb
    restart: always
    ports:
      - "8812:8812"
      - "9000:9000"
      - "9009:9009"
      - "9003:9003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - QDB_METRICS_ENABLED=TRUE
      - QDB_CAIRO_MAT_VIEW_ENABLED=true
    volumes:
      - ./questdb/questdb_root:/var/lib/questdb/:rw

  grafana:
    image: grafana/grafana-oss:11.2.0
    container_name: trading_demo_grafana
    restart: always
    user: "${DOCKER_COMPOSE_USER_ID:-}"
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./dashboard/grafana/home_dir/var_lib_grafana:/var/lib/grafana/:rw
      - ./dashboard/grafana/home_dir/etc_grafana:/etc/grafana/:rw
    environment:
      - GF_INSTALL_PLUGINS=questdb-questdb-datasource
      - QDB_CLIENT_HOST=${QDB_CLIENT_HOST:-host.docker.internal}
      - QDB_CLIENT_PORT=${QDB_CLIENT_PORT:-8812}
      - QDB_CLIENT_USER=${QDB_CLIENT_USER:-admin}
      - QDB_CLIENT_PASSWORD=${QDB_CLIENT_PASSWORD:-quest}
      # use the value "disable" for local installations, and "require" for QuestDB Cloud
      - QDB_SSL_MODE=${QDB_SSL_MODE:-disable}

  jupyter-notebook:
    image:    jupyter/scipy-notebook
    container_name: trading_demo_jupyter
    volumes:
      - ./notebooks:/home/jovyan:rw
      - ./ingestion/python:/home/ingestion:rw
      - ./questdb/questdb_root:/db_root:ro
    ports:
      - 8888:8888
    command: sh -c "pip install questdb databento psycopg[binary] psycopg2-binary requests && start-notebook.sh --NotebookApp.password= --NotebookApp.token="
    depends_on:
      - questdb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - RESTARTABLE=yes
      - DATABENTO_API_KEY=${DATABENTO_API_KEY}
      - DOCKER_STACKS_JUPYTER_CMD=notebook
      - QUESTDB_HTTP_ENDPOINT=${QUESTDB_HTTP_ENDPOINT:-host.docker.internal:9000}
      - QDB_CLIENT_HOST=${QDB_CLIENT_HOST:-host.docker.internal}
      - QDB_CLIENT_PORT=${QDB_CLIENT_PORT:-8812}
      - QDB_CLIENT_USER=${QDB_CLIENT_USER:-admin}
      - QDB_CLIENT_PASSWORD=${QDB_CLIENT_PASSWORD:-quest}

