{
 "title": "Trades - Crypto Currency",
 "description": "Trading dashboard using the trades dataset",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "250ms",
 "panels": [
  {
   "title": "Latest trades",
   "type": "table",
   "description": "Real-time buy and sell orders.",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, \nleft(symbol,strpos(symbol,'-')-1) asset,\nright(symbol,length(symbol)-strpos(symbol,'-')) counter,\ncase when side = 'buy' then amount else -amount end quantity, \ncase when side = 'buy' then -amount*price else amount*price end consideration,\ncase when (now()-timestamp)/1000000<0.3 then 'x' else '' end new\nfrom trades where $__timeFilter(timestamp) order by timestamp desc\nlimit 50",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Real-time trades",
   "type": "timeseries",
   "description": "Filled exchange orders between a few crypto assets, with USDT notional along the y-axis. Positive values are buy orders, negative are sell orders.",
   "gridPos": { "h": 10, "w": 9, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp time, symbol,\n  AVG(case when side ='buy' then amount*price \n  else -1*amount*price end) trade \nfrom trades where $__timeFilter(timestamp) and \nsymbol like '%-USDT' SAMPLE BY 250T"
    }
   ]
  },
  {
   "title": "Volume heatmap",
   "type": "state-timeline",
   "description": "Trade volume (USD notional) distribution per asset for the past 5 minutes.",
   "gridPos": { "h": 9, "w": 13, "x": 1, "y": 10 },
   "targets": [
    {
     "rawSql": "select timestamp time, left(symbol,strpos(symbol,'-')-1) asset, sum(abs(amount)) from \ntrades where $__timeFilter(timestamp) and \nright(symbol,length(symbol)-strpos(symbol,'-'))= 'USDT'\nsample by 5s\norder by time, asset\n"
    }
   ]
  },
  {
   "title": "Moving averages for Bitcoin price",
   "type": "timeseries",
   "description": "Moving averages on the USD price of Bitcoin in the past 5 minutes, over 10-, 30-, and 45-second windows.",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT timestamp time, symbol, price as priceBtc\n, avg(price) over (PARTITION BY symbol ORDER BY timestamp RANGE between 30 seconds PRECEDING AND CURRENT ROW) movingAvg30Sec\n, avg(price) over (PARTITION BY symbol ORDER BY timestamp RANGE between 45 seconds PRECEDING AND CURRENT ROW) movingAvg45Sec\nFROM ((\n  select timestamp, symbol, avg(price) price from trades\n  WHERE $__timeFilter(timestamp) AND symbol = 'BTC-USDT'\n  SAMPLE by 1s\n  order by 1\n)timestamp(timestamp));",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Bitcoin Candlestick Chart (OHLC)",
   "type": "candlestick",
   "description": "An OHLC (Open, High, Low, Close) chart for the notional price in USD of Bitcoin, sampled every second over the past 5 minutes.",
   "gridPos": { "h": 6, "w": 13, "x": 1, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, first(price) as open, last(price) as close, min(price) as lo, max(price) as hi, sum(amount) as vol\nFROM trades\nWHERE symbol = 'BTC-USDT' and $__timeFilter(timestamp) \nSAMPLE BY 5s ALIGN TO CALENDAR",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Rolling BTC-ETH correlation coefficient",
   "type": "timeseries",
   "description": "Calculation of the Pearson correlation coefficient (ρ) between the prices of Ethereum and Bitcoin. Data is sampled every minute over the past 12 hours, and correlation is calculated over hour- and day-long windows.",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 19 },
   "targets": [
    {
     "rawSql": "WITH data as (\nWITH \nBTCUSD as (select timestamp, price from trades where $__timeFilter(timestamp) and symbol = 'BTC-USDT' ),\nETHUSD as (select timestamp, price from trades where $__timeFilter(timestamp) and symbol = 'ETH-USDT' )\nSELECT BTCUSD.timestamp, corr(BTCUSD.price,ETHUSD.price) from BTCUSD asof join ETHUSD sample by 10s)\nSELECT timestamp\n, avg(corr) over(ORDER BY timestamp range between 1 minute preceding and current row) one_min_corr_rolling\n, avg(corr) over(ORDER BY timestamp range between 5 minute preceding and current row) five_min_corr_rolling\nfrom data",
     "selectedFormat": 2
    }
   ]
  }
 ]
}